blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Course Documentation
    url: https://github.com/Matnazar-Matnazarov/vanilla-js-learning#readme
    about: Check the README for course information

